from construct import *

"""Achievements snapshot taken at the start of the recorded game, not the end"""
player_achievements = Struct("ach",
	Padding(13),
	ULInt32("total_points"),
	Padding(26),
	ULInt32("war_points"),
	Padding(34),
	LFloat32("num_kills"),
	Padding(28),
	LFloat32("num_killed"),
	Padding(28),
	LFloat32("num_killed2"),
	Padding(284),
	Padding(4),
	Padding(60),
	Padding(4),
	Padding(444),
	LFloat32("total_food"),
	Padding(28),
	LFloat32("total_wood"),
	Padding(28),
	LFloat32("total_stone"),
	Padding(28),
	LFloat32("total_gold"),
	Padding(444),
	LFloat32("max_villagers"),
	Padding(28),
	LFloat32("max_villages2"),
	Padding(28),
	LFloat32("relic_castle"),
	Padding(28),
	LFloat32("relic_castle2"),
	Padding(28),
	LFloat32("wonder"),
	Padding(28),
	LFloat32("relic_gold"),
	Padding(124),
	LFloat32("researched_techs"),
	Padding(28),
	LFloat32("explored_percent"),
	Padding(4),
)

"""Achievements exist for all players but Gaia"""
achievements = Array(lambda ctx: ctx.replay.num_players - 1, player_achievements)